//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeedbackSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public System.Guid Id { get; set; }
        public string ShortDesc { get; set; }
        public string LongDesc { get; set; }
        public bool Positive { get; set; }
        public string Date { get; set; }
        public System.Guid UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
